version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    json_formatter:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    console2:
        class: kedro.extras.logging.ColorHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
        # defining colors is optional
        colors:
            debug: magenta
            info: green
            warning: yellow
            error: red

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    journal_file_handler:
        class: kedro.versioning.journal.JournalFileHandler
        level: INFO
        base_dir: logs/journals
        formatter: json_formatter

loggers:
    anyconfig:
        level: WARNING
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kedro.io:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kedro.pipeline:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kedro.journal:
        level: INFO
        handlers: [journal_file_handler]
        propagate: no

    phantasyfootballer.data_import:
        level: DEBUG
        handlers: [console2]
        propagate: no

    phantasyfootballer:
        level: DEBUG
        handlers: [console2]
        propagate: no

    data_engineering.node:
        level: DEBUG
        handlers: [console2]
        propagate: no

root:
    level: DEBUG
    #handlers: [console, info_file_handler, error_file_handler]
    handlers: [console]
