
# Parameters that affect the pipelines

stat_providers:
    fantasyfootballdatapros:
        stat_map:
            player: Player
            team: Tm
            position: Pos
            pos_rank: Rk
            pass_att: PassingAtt
            pass_comp: Cmp
            pass_yds: PassingYds
            pass_tds: PassingTD
            pass_int: Int
            rush_att: RushingAtt
            rush_yds: RushingYds
            rush_tds: RushingTD
            rcv_rec: Rec
            rcv_tgt: Tgt
            rcv_yds: ReceivingYds
            rcv_tds: ReceivingTD
            misc_fl: FL

# Minimum number of projected points
#  and maximum number of players by position
# Order of precedence is minimum points then maximum players
player_filter:
    remove: True
    _all_positions: &all_positions
        min_fp: 10
        max_players: 100
    QB:
        <<: *all_positions
        max_players: 40
    RB: 
        <<: *all_positions
        min_fp: 50
    WR: 
        min_fp: 50
        max_players: 100
    TE: 
        max_players: 40
        min_fp: 30