
# Parameters that affect the pipelines

stat_providers:
    fantasyfootballdatapros:
        stat_map:
            player: Player
            team: Tm
            position: Pos
            pos_rank: Rk
            pass_att: PassingAtt
            pass_comp: Cmp
            pass_yds: PassingYds
            pass_tds: PassingTD
            pass_int: Int
            rush_att: RushingAtt
            rush_yds: RushingYds
            rush_tds: RushingTD
            rcv_rec: Rec
            rcv_tgt: Tgt
            rcv_yds: ReceivingYds
            rcv_tds: ReceivingTD
            misc_fl: FL
    